[phases.setup]
nixPkgs = ["nodejs-18_x"]
aptPkgs = [
  "chromium",
  "chromium-sandbox",
  "fonts-liberation",
  "libappindicator3-1",
  "libasound2",
  "libatk-bridge2.0-0",
  "libatk1.0-0",
  "libcups2",
  "libdbus-1-3",
  "libgbm1",
  "libgtk-3-0",
  "libnspr4",
  "libnss3",
  "libx11-xcb1",
  "libxcomposite1",
  "libxdamage1",
  "libxrandr2",
  "xdg-utils"
]

[phases.install]
cmds = [
  "npm install --workspace=backend --prefer-offline --no-audit --progress=false"
]

[phases.build]
cmds = [
  "npm run build --workspace=backend"
]

[start]
cmd = "npm run start --workspace=backend"

[variables]
NODE_ENV = "production"
PUPPETEER_SKIP_DOWNLOAD = "false"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
