[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "npm install --workspace=backend"
]

[phases.build]
cmds = [
  "npm run build --workspace=backend"
]

[start]
cmd = "npm run start --workspace=backend"

[variables]
NODE_ENV = "production"
PUPPETEER_SKIP_DOWNLOAD = "true"
