[phases.setup]
nixPkgs = ["nodejs-18_x", "chromium"]

[phases.install]
cmds = [
  "npm install --workspace=backend --prefer-offline --no-audit --progress=false"
]

[phases.build]
cmds = [
  "npm run build --workspace=backend"
]

[start]
cmd = "npm run start --workspace=backend"

[variables]
NODE_ENV = "production"
PUPPETEER_SKIP_DOWNLOAD = "false"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
